# Generated by Django 2.1.2 on 2018-10-09 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('checkin', models.DateField(default=datetime.datetime(2018, 10, 9, 14, 16, 51, 603801, tzinfo=utc))),
                ('checkout', models.DateField(default=datetime.datetime(2018, 10, 9, 14, 16, 51, 603801, tzinfo=utc))),
                ('type', models.CharField(max_length=140)),
            ],
        ),
    ]
