# Generated by Django 2.1.2 on 2018-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripHotelSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('numberOfPersons', models.CharField(max_length=140)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
